#no need to meniton the version of docker-compose as it is optional for version v2.33.1

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=jira_developments #database name by default
    ports:
      - "5432:5432"
    networks:
      - jira_network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  api:
    container_name: jira_api
    restart: unless-stopped
    image: jira-api-prod:92.1 #image name with version I defined
    build:
      context: api
      target: production
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - jira_network
    depends_on:
      - postgres #depends on postgres service

  client:
    container_name: jira_client
    restart: unless-stopped
    image: jira-client-prod:92.1 #image name with version I defined
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    networks:
      - jira_network
    depends_on:
      - api #depends on postgres service

networks:
  jira_network:
